### ISSUE TITLE
Enhancement: Back Button

### ISSUE THREAD

**Issue by pmsaue0** [colby-swandale/honeybird#1]
I really like this little shell for the player, thank you for putting it together :)  What do you think about creating a keyboard shortcut for the browser back button?  Perhaps mapped to Delete.

Use case:
When browsing an artist page and I click an album to view the songs in that album, I'd like to be able to easily return to that artist page.  (without having to initialize another search for that artist or start over from the home page)

**Comment by pmsaue0** [comment]
I just used this, but it's probably not for everyone.  

```javascript
globalShortcut.register('F6', function() {
    mainWindow.webContents.goBack();
  });
```

Command+Delete didn't work for me, so I just mapped to F6

**Comment by colby-swandale** [comment]
I have had this issue arise several times myself, i have been testing around with mapping the delete button to go back. Most browsers follow this same keymap and it would play nice on all platforms.
